---

services:
  searxng:
    image: searxng/searxng:latest
    environment:
      - FORWARDED_ALLOW_IPS=*
    volumes:
      - ./etc:/etc/searxng
    ports:
      - "${PORT:-8080}:8080"
    restart: unless-stopped
